---
- name: Wait for server to be ready
  hosts: artifactory
  gather_facts: false
  vars:
    ansible_connection: local
  tasks:
    - name: Wait for ssh port open
      ansible.builtin.wait_for:
        port: 22
        delay: 15
        timeout: 75
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    


- name: Update apt
  hosts: artifactory
  tasks:
    - name: Update apt
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 4000
      become: yes


- name: Download and unpack Artifactory
  hosts: artifactory
  vars_files:
    - artifactory/vars/db_vars.yaml
    - artifactory/vars/playbook_vars.yaml
  tasks:
    - name: Make Artifactory installation directory
      ansible.builtin.command:
        cmd: mkdir -p /usr/local/jfrog/artifactory
      become: yes
    
    - name: Set artifactory environment variables
      ansible.builtin.blockinfile:
        
        path: /home/ec2-user/.bashrc
        block: |
          export JFROG_HOME=/usr/local/jfrog
          export DB_USER={{DB_USER}}
          export DB_PASS={{DB_PASSWORD}}
          export DB_NAME={{DB_NAME}}
        insertafter: EOF
        prepend_newline: true
      become: yes
    
    - name: Get Artifactory linux archive
      ansible.builtin.get_url:
        dest: /usr/local/jfrog/artifactory.tar.gz
        url: https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/jcr/jfrog-artifactory-jcr/{{artifactory_version}}/jfrog-artifactory-jcr-{{artifactory_version}}-linux.tar.gz
        decompress: false
      become: yes

    - name: Extract archive
      ansible.builtin.command:
        chdir: /usr/local/jfrog
        cmd: tar -xvf ./artifactory.tar.gz -C artifactory --strip-components=1
      become: yes

- name: Retrieve DB CA Certs
  hosts: artifactory
  vars_files:
    - artifactory/vars/db_vars.yaml
  tasks:
    - name: Get Microsoft Root CA
      ansible.builtin.get_url:
        dest: /usr/local/jfrog/microsoft.crt
        url: 'https://www.microsoft.com/pkiops/certs/Microsoft%20RSA%20Root%20Certificate%20Authority%202017.crt'
        decompress: false
      become: yes

    - name: Get DigiCert Root CA
      ansible.builtin.get_url:
        dest: /usr/local/jfrog/digicert.crt.pem
        url: 'https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem'
        decompress: false
      become: yes
    
    - name: Convert Microsoft crt 
      ansible.builtin.command:
        chdir: /usr/local/jfrog
        cmd: openssl x509 -inform DER -in microsoft.crt -out microsoft.pem -outform PEM
      become: yes
    
    - name: Create combined.pem
      ansible.builtin.command:
        cmd: touch /usr/local/jfrog/combined.pem
      become: yes
    
    - name: Change ownership of combined.pem
      ansible.builtin.command:
        cmd: chown {{LINUX_ADMIN}} /usr/local/jfrog/combined.pem
      become: yes

    - name: Combine pem 
      ansible.builtin.shell:
        chdir: /usr/local/jfrog
        cmd: cat digicert.crt.pem > combined.pem && cat microsoft.pem >> combined.pem
      become: yes

- name: Artifactory DB Setup
  hosts: artifactory
  vars_files:
    - artifactory/vars/db_vars.yaml
  tasks:
    - name: Setup Artifactory service
      ansible.builtin.command:
        cmd: /usr/local/jfrog/artifactory/app/bin/installService.sh
      become: yes
    
    - name: Copy db_conf file
      ansible.builtin.copy:
        dest: /usr/local/jfrog/db_conf.yaml
        src: artifactory/db_conf.yaml
      become: yes
    
    - name: Copy db_conf to system.yaml
      ansible.builtin.shell:
        cmd: cat /usr/local/jfrog/db_conf.yaml > /usr/local/jfrog/artifactory/var/etc/system.yaml
      become: yes
    
    - name: Copy env keys into system.yaml
      ansible.builtin.lineinfile:
        path: /usr/local/jfrog/artifactory/var/etc/system.yaml
        line: "    url: jdbc:postgresql://{{DB_ENDPOINT}}:5432/{{DB_NAME}}?sslrootcert=/usr/local/jfrog/combined.pem&sslmode=verify-full \n    username: {{DB_USER}}\n    password: {{DB_PASSWORD}}"
        insertafter: EOF
      become: yes

- name: Run Artifactory
  hosts: artifactory
  tasks:
    - name: Start Artifactory service
      ansible.builtin.command:
        cmd: systemctl start artifactory.service
      become: yes